image: emeris/sdk-service:latest
imagePullPolicy: IfNotPresent

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 200m
    memory: 256Mi

ports:
  grpc: 9090

debug: true