name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - cmd/**
      - go.mod
      - go.sum
      - grpc_cosmos_sdk_*.go
      - sdk_utilities.go
      - helm/**

jobs:
  prepare-version-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: set-matrix
        run: echo "::set-output name=matrix::$(jq [.[].version] sdk_targets.json)"

    # here, we save the result of this 1st phase to the "outputs"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  use-matrix:
    needs: prepare-version-matrix
    runs-on: ubuntu-latest
    strategy:
      # ↓ the real magic happens here - create dynamic matrix from the json
      matrix:
        package: ${{ fromJson(needs.prepare-version-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        run: echo ${{ matrix.package }}

  sdk-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-sdk-service:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-sdk-service:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}
